version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: go test ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
